spring:
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:carsdb
    driverClassName: org.h2.Driver
    username: suse
    password: suse
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always